In [1]:
import pandas as pd
import numpy as np

In [5]:
#np.random.seed(20)
arr = np.random.randint(low = 1,high = 100,size = (3,4))
print(arr)

[[52 72 44 54]
 [52 88 29 77]
 [35 59 23 46]]


In [9]:
df = pd.DataFrame(arr,index = ["sun","mon","wed"],columns = ["jan","feb","march","april"])
print(df)

     jan  feb  march  april
sun   52   72     44     54
mon   52   88     29     77
wed   35   59     23     46
